pipeline {
    agent {label 'worker-node'}
    environment {
        DOCKER_CRED = credentials('iniyan-dockerhub')
    }

    stages {
        stage('Docker Build') {
            steps {
                sh 'docker build -t iniyan/alpine:latest .'
            }
        }
        
        stage('Docker Login') {
            steps {
                sh 'echo $DOCKER_CRED_PSW | docker login -u $DOCKER_CRED_USR --password-stdin'
            }
        }

        stage('Docker Push') {
            steps {
                sh 'docker push iniyan/alpine:latest'
            }
        }

        stage('Docker Logout') {
            steps {
                sh 'docker logout'
            }
        }
    }
}