pipeline {
    agent {label 'worker-node'}

    stages {
        stage('Check Tooling') {
            steps {
                sh '''
                docker version
                docker info
                docker-compose version
                curl --version
                jq --version
            '''
            }
        }

        stage('Prune Docker Data') {
            steps {
                // --all -> Remove all unused images not just dangling ones
                // --volumes -> Prune volumes
                sh '''
                docker system prune --all --volumes -f
                '''
            }
        }

        stage('Docker Compose Up') {
            steps {
                // --wait -> Wait for services to be running|healthy. Implies detached mode
                // -d ->  Detached mode: Run containers in the background
                sh '''
                docker-compose -f docker-compose-example/docker-compose.yaml up -d --no-color --wait 
                docker-compose -f docker-compose-example/docker-compose.yaml ps
                '''
            }
        }

        stage('Run Test againt the Echo Server Container') {
            steps {
                // Ref: https://hub.docker.com/r/ealen/echo-server
                sh 'curl http://localhost:3000/param?query=demo'
                
            }
        }
    }

    post {
        always {
            //--remove-orphans -> Remove containers for services not defined in the Compose file.
            // -v ->  Remove named volumes declared in the volumes section of the Compose file and anonymous volumes attached to containers.
            sh 'docker-compose -f docker-compose-example/docker-compose.yaml down --remove-orphans -v'
        }
    }
}